### PR TITLE
[cleanup] Suppression of variables declared in tests abstract superclass

### PR DESCRIPTION
**Pull request by ebausson-obeo**
Three variables duplicated in some child classes are removed from said sublclasses:
 * SWTBotSiriusDiagramEditor editor
 * UIResource sessionAirdResource
 * UILocalSession localSession

### CODE REVIEW

**Comment by ebausson-obeo** [comment]
cleaner version of PR: https://github.com/eclipse-sirius/sirius-desktop/pull/147

**Comment by pcdavid** [comment]
Technically all modified files should get their copyright header updated to indicate "2023" (if that's not already the case). I personally don't care, but others do :wink:

**Review by lredor — CHANGES_REQUESTED** [review]
So as said by @pcdavid, a change of the copyright header of the impacted classes and it will be perfect.

**Comment by ebausson-obeo** [comment]
Headers modified for updated copyrights.

**Review by pcdavid — APPROVED** [review]

**Review by lredor — APPROVED** [review]

**Pull request merged**
