### PR TITLE
[203] Upgrade to ELK 0.9.0

### PR DESCRIPTION
**Pull request by lredor**
Bug: https://github.com/eclipse-sirius/sirius-desktop/issues/203

### CODE REVIEW

**Comment by lredor** [comment]
This PR should not be merged. I push it just to have tests result. At least locally, there are 24 failures to fix on org.eclipse.sirius.tests.unit.diagram.layout.SimpleELKLayoutTest. I'll take a look at it next year after the holidays.

**Comment by pcdavid** [comment]
Converted to a _darft_ to make it clear that it's not ready yet.

**Comment by lredor** [comment]
> This PR should not be merged. I push it just to have tests result. At least locally, there are 24 failures to fix on org.eclipse.sirius.tests.unit.diagram.layout.SimpleELKLayoutTest. I'll take a look at it next year after the holidays.

It seems that some ELK options have been "renamed" between ELK 0.7.1 and ELK 0.9.0. I've posted a message to know how to have the complete list on [gitter](https://matrix.to/#/!hFJKlkXrdolGTZEIdx:gitter.im/$_M6gIB__6DZe1GcUusfbFdm5L1Ic3aJWczfRYabzg2w?via=gitter.im&via=matrix.org&via=tf.uni-kiel.de).

**Comment by lredor** [comment]
This PR now includes a migration participant to correctly migrate the impacted options between ELK 0.7.1 and ELK 0.9.0. All options have been handled after [discussions](https://matrix.to/#/!hFJKlkXrdolGTZEIdx:gitter.im/$_M6gIB__6DZe1GcUusfbFdm5L1Ic3aJWczfRYabzg2w?via=gitter.im&via=matrix.org&via=tf.uni-kiel.de) with ELK team. The ELK release notes have been completed after my remarks.

Some problem remains in the Sirius code itself (no longer with the options stored in the VSM).

Maybe, a specific test could be added with this VSM file containing all the impacted options.
[ELK0.7.1-0.9.0-changes.odesign.zip](https://github.com/eclipse-sirius/sirius-desktop/files/13844998/ELK0.7.1-0.9.0-changes.odesign.zip)

**Comment by lredor** [comment]
> Some problem remains in the Sirius code itself (no longer with the options stored in the VSM).

Pb solved in the last commit !

**Comment by lredor** [comment]
Autmatic test and release notes have been added. Everything is OK on my side.

**Review by lfasani — APPROVED** [review]

**Pull request merged**
