### PR TITLE
[162] Ensure compatibility with Eclipse 2023-12

### PR DESCRIPTION
**Pull request by pcdavid**
- [162] Move to GMF Runtime 1.16.2 and Apache Batik 1.17
- [162] Adapt to upcoming GEF Classic
- [162] Add 2023-12 target platform
- [162] Fix canary target platform
- [162] Update our Guava ranges

### CODE REVIEW

**Review by lfasani — APPROVED** [review]

**Comment by pcdavid** [comment]
Actually we can not open our Guava ranges quite yet, as Acceleo & EMF Compare use the same ranges as us, and if we don't sync we (Sirius) get Guava 32 while they (Accelo & Compare) get Guava 30, causing all kinds of errors at runtime (or at least during the tests) like:

> loader constraint violation: when resolving field "errors" of type com.google.common.collect.Multimap

**Comment by pcdavid** [comment]
It seems the Draw2D-related failures mentioned above are false positives. Something specific to my environment.

However, running the tests on our CI (with the Guava change reverted to avoid compatibility issues with Acceleo & EMF Compare) reveals other failures that I don't understand yet and look possibly scary. They did not occur with `sirius_2023-03.target` but are visible when using `sirius_2023-12.target`.

First batch of failures:
```
org.eclipse.sirius.tests.unit.diagram.format.data.MappingBasedSiriusFormatDataManagerCreateTargetSequenceDiagramDiffSessionTest
org.eclipse.sirius.tests.unit.diagram.format.data.MappingBasedSiriusFormatDataManagerCallCheckTest
org.eclipse.sirius.tests.unit.diagram.format.data.MappingBasedSiriusFormatDataManagerCallCheckSequenceTest
```

These are almost 100% failing with messages like:

```
java.lang.RuntimeException: Impossible to create the session.
	at org.eclipse.sirius.tests.unit.diagram.format.data.MappingBasedSiriusFormatDataManagerCreateTargetDiagramDiffSessionTest.setUp(MappingBasedSiriusFormatDataManagerCreateTargetDiagramDiffSessionTest.java:66)
Caused by: org.eclipse.core.runtime.CoreException: Session creation failed
	at org.eclipse.sirius.tests.unit.diagram.format.data.MappingBasedSiriusFormatDataManagerCreateTargetDiagramDiffSessionTest.setUp(MappingBasedSiriusFormatDataManagerCreateTargetDiagramDiffSessionTest.java:66)
Caused by: java.net.UnknownServiceException: protocol doesn't support output
	at org.eclipse.sirius.tests.unit.diagram.format.data.MappingBasedSiriusFormatDataManagerCreateTargetDiagramDiffSessionTest.setUp(MappingBasedSiriusFormatDataManagerCreateTargetDiagramDiffSessionTest.java:66)
```

Second batch:
```
org.eclipse.sirius.tests.unit.diagram.format.data.SiriusFormatDataManagerForSemanticElementsTest
org.eclipse.sirius.tests.unit.diagram.format.data.MappingBasedSiriusFormatDataManagerTest
```
fail with "The number of expected diagrams is wrong expected:<2> but was:<0>"

And finally:
```
org.eclipse.sirius.tests.unit.diagram.format.data.SiriusFormatDataManagerForSemanticElementsStoreWithPredefinedDataTest
```
lots of failures with messages like:

> java.io.FileNotFoundException: /data/unit/layout/data/3.5/xmi/storedFormat-DiagType2__of__MyPackage.xmi

where from what I can tell the files mentioned all exist.

**Comment by pcdavid** [comment]
The first batch is the most scary with the following stack:

```
org.eclipse.emf.ecore.resource.impl.URIHandlerImpl.createOutputStream(org.eclipse.emf.common.util.URI, java.util.Map<?,?>) line: 154
org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createOutputStream(org.eclipse.emf.common.util.URI, java.util.Map<?,?>) line: 347
org.eclipse.sirius.business.internal.resource.AirDResourceImpl(org.eclipse.emf.ecore.resource.impl.ResourceImpl).save(java.util.Map<?,?>) line: 1041
org.eclipse.sirius.business.internal.session.SessionFactoryImpl.prepareDAnalysis(org.eclipse.emf.common.util.URI, org.eclipse.emf.transaction.TransactionalEditingDomain, org.eclipse.core.runtime.IProgressMonitor, org.eclipse.emf.ecore.resource.Resource, java.lang.String) line: 279
org.eclipse.sirius.business.internal.session.SessionFactoryImpl.createSessionResource(org.eclipse.emf.common.util.URI, org.eclipse.emf.transaction.TransactionalEditingDomain, boolean, org.eclipse.core.runtime.IProgressMonitor) line: 237
org.eclipse.sirius.business.internal.session.SessionFactoryImpl.createSession(org.eclipse.emf.common.util.URI, org.eclipse.core.runtime.IProgressMonitor) line: 89
org.eclipse.sirius.business.api.session.DefaultLocalSessionCreationOperation.execute() line: 70
org.eclipse.sirius.tests.support.api.SiriusTestCase$2.execute(org.eclipse.core.runtime.IProgressMonitor) line: 464
```

EMF's `URIHandlerImpl` does:
```java
OutputStream outputStream = uriConverter.createOutputStream(uri, effectiveOptions);
```

Where:
* `uri` is `platform:/plugin/org.eclipse.sirius.tests.junit/data/unit/layout/mappingbased/3.5/My.aird`
* `uriConverter` is a `org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl`

**Comment by pcdavid** [comment]
False alert, this was all due to a dumb bug in our own code which should be fixed by https://github.com/eclipse-sirius/sirius-desktop/pull/163/commits/391ab6e40a9377e161653526d55fe5466e035dba.

**Pull request merged**
